[project]
name = "zth"
version = "0.1.0"
description = "zero to hero"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
 "graphviz>=0.21",
 "ipykernel>=7.1.0",
 "jupyterlab>=4.5.0",
 "matplotlib>=3.10.7",
 "numpy>=2.3.5",
 "transformers>=4.57.3",
]
